### PR TITLE
New settings page. Revert to gestures using LVGL

### PR DESCRIPTION
**Pull request by jakkra**
See commits.

### CODE REVIEW

**Comment by Kampi** [comment]
I think it´s a good idea to add the following changes:

- Rename "General" to "Display"
- Move "Screen" (what is it exactly?) from "Other" to "Display"
- Move "Vibrate" and "Reset Step Counter" from "Display" to "Other"

Also the "Back" button (top left) doesn´t work. Instead, it scrolls through the menu and swipes up to open "Settings" and also opens "General" often.

**Comment by jakkra** [comment]
> I think it´s a good idea to add the following changes:
> 
> * Rename "General" to "Display"
> * Move "Screen" (what is it exactly?) from "Other" to "Display"
> * Move "Vibrate" and "Reset Step Counter" from "Display" to "Other"
> 
> Also the "Back" button (top left) doesn´t work. Instead, it scrolls through the menu and swipes up to open "Settings" and also opens "General" often.

Good idea, will do like that. 
Back button never worked with touch, but handy for navigating in posix and with buttons. It should be moved a bit.

**Comment by Kampi** [comment]
> > I think it´s a good idea to add the following changes:
> > 
> > * Rename "General" to "Display"
> > * Move "Screen" (what is it exactly?) from "Other" to "Display"
> > * Move "Vibrate" and "Reset Step Counter" from "Display" to "Other"
> > 
> > Also the "Back" button (top left) doesn´t work. Instead, it scrolls through the menu and swipes up to open "Settings" and also opens "General" often.
> 
> Good idea, will do like that. Back button never worked with touch, but handy for navigating in posix and with buttons. It should be moved a bit.

Haven´t tested it with touch. It was the regular button. :P

**Comment by jakkra** [comment]
> > > I think it´s a good idea to add the following changes:
> > > 
> > > * Rename "General" to "Display"
> > > * Move "Screen" (what is it exactly?) from "Other" to "Display"
> > > * Move "Vibrate" and "Reset Step Counter" from "Display" to "Other"
> > > 
> > > Also the "Back" button (top left) doesn´t work. Instead, it scrolls through the menu and swipes up to open "Settings" and also opens "General" often.
> > 
> > 
> > Good idea, will do like that. Back button never worked with touch, but handy for navigating in posix and with buttons. It should be moved a bit.
> 
> Haven´t tested it with touch. It was the regular button. :P

Hmm, the back button in settings work as expected for me.

**Comment by Kampi** [comment]
> > > > I think it´s a good idea to add the following changes:
> > > > 
> > > > * Rename "General" to "Display"
> > > > * Move "Screen" (what is it exactly?) from "Other" to "Display"
> > > > * Move "Vibrate" and "Reset Step Counter" from "Display" to "Other"
> > > > 
> > > > Also the "Back" button (top left) doesn´t work. Instead, it scrolls through the menu and swipes up to open "Settings" and also opens "General" often.
> > > 
> > > 
> > > Good idea, will do like that. Back button never worked with touch, but handy for navigating in posix and with buttons. It should be moved a bit.
> > 
> > 
> > Haven´t tested it with touch. It was the regular button. :P
> 
> Hmm, the back button in settings work as expected for me.

I tested it on rev 3. Let me repeat it and make a video to show it.

**Pull request merged**
