### PR TITLE
Upgrade to nRF Connect 2.7.

### PR DESCRIPTION
**Pull request by jakkra**

### CODE REVIEW

**Comment by Kampi** [comment]
Get this message

image

**Comment by Kampi** [comment]
BSEC doesn´t work

image

**Comment by jakkra** [comment]
Ci also fails, I'll wlak through it all again tomorrow.

**Comment by Kampi** [comment]
> Ci also fails, I'll go through it all again tomorrow.

Yeah no stress. I´m checking the BSEC issue already. I think it´s a wrong path in CMakeLists.

**Comment by Kampi** [comment]
Implicit functions

image

**Comment by Kampi** [comment]
Revision 5 in the debug configuration was also built successfully

**Comment by jakkra** [comment]
> Implicit functions
> 
> image

Yeah those we hade before also, don't know why they are back.

**Review by Kampi — APPROVED** [review]

**Pull request merged**
