### PR TITLE
Fix gadgetbridge parsing + BSEC fixes and improvements

### PR DESCRIPTION
**Pull request by jakkra**
- Fixes Gadgetbridge parsing missing last 3 characters. Cased notification read from phone not remove them on watch.
- Some renaming needed for BSEC to work as configs are the same in NCS.
- Easier download of bsec library.
- Some minor fixes.

### CODE REVIEW

**Review by Kampi — COMMENTED** [review]
Got the error

```
ninja: error: '../src/ext_drivers/BSEC2/src/cortex-m4/libalgobsec.a', needed by 'zephyr/zephyr_pre0.elf', missing and no known rule to make it
FATAL ERROR: command exited with status 1: 'C:\ncs\toolchains\31f4403e35\opt\bin\cmake.EXE' --build 'f:\Git\ZSWatch\app\build_rev_3'
```

when building with BSEC enabled.

**Comment by jakkra** [comment]
> Got the error
> 
> ```
> ninja: error: '../src/ext_drivers/BSEC2/src/cortex-m4/libalgobsec.a', needed by 'zephyr/zephyr_pre0.elf', missing and no known rule to make it
> FATAL ERROR: command exited with status 1: 'C:\ncs\toolchains\31f4403e35\opt\bin\cmake.EXE' --build 'f:\Git\ZSWatch\app\build_rev_3'
> ```
> 
> when building with BSEC enabled.

Ok, will check again and also add so there is one build in CI that enables this (or all)

**Comment by jakkra** [comment]
Wrong in my instructions, should be west config manifest.group-filter +bsec**2** not just bsec

**Comment by Kampi** [comment]
> > Got the error
> > ```
> > ninja: error: '../src/ext_drivers/BSEC2/src/cortex-m4/libalgobsec.a', needed by 'zephyr/zephyr_pre0.elf', missing and no known rule to make it
> > FATAL ERROR: command exited with status 1: 'C:\ncs\toolchains\31f4403e35\opt\bin\cmake.EXE' --build 'f:\Git\ZSWatch\app\build_rev_3'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > when building with BSEC enabled.
> 
> Ok, will check again and also add so there is one build in CI that enables this (or all)

Looks like the path in the `CMakeLists.txt` of the driver got messed up.

https://github.com/jakkra/ZSWatch/blob/main/app/drivers/sensor/bme68x_iaq/CMakeLists.txt

After undoing the changes the issue is gone.

**Comment by jakkra** [comment]
> > > Got the error
> > > ```
> > > ninja: error: '../src/ext_drivers/BSEC2/src/cortex-m4/libalgobsec.a', needed by 'zephyr/zephyr_pre0.elf', missing and no known rule to make it
> > > FATAL ERROR: command exited with status 1: 'C:\ncs\toolchains\31f4403e35\opt\bin\cmake.EXE' --build 'f:\Git\ZSWatch\app\build_rev_3'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > when building with BSEC enabled.
> > 
> > 
> > Ok, will check again and also add so there is one build in CI that enables this (or all)
> 
> Looks like the path in the `CMakeLists.txt` of the driver got messed up.
> 
> https://github.com/jakkra/ZSWatch/blob/main/app/drivers/sensor/bme68x_iaq/CMakeLists.txt
> 
> After undoing the changes the issue is gone.

No, the change is correct, the paths slightly changed. I fixed the instructions now to say 
west config manifest.group-filter +bsec2

**Comment by Kampi** [comment]
> > > > Got the error
> > > > ```
> > > > ninja: error: '../src/ext_drivers/BSEC2/src/cortex-m4/libalgobsec.a', needed by 'zephyr/zephyr_pre0.elf', missing and no known rule to make it
> > > > FATAL ERROR: command exited with status 1: 'C:\ncs\toolchains\31f4403e35\opt\bin\cmake.EXE' --build 'f:\Git\ZSWatch\app\build_rev_3'
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > when building with BSEC enabled.
> > > 
> > > 
> > > Ok, will check again and also add so there is one build in CI that enables this (or all)
> > 
> > 
> > Looks like the path in the `CMakeLists.txt` of the driver got messed up.
> > https://github.com/jakkra/ZSWatch/blob/main/app/drivers/sensor/bme68x_iaq/CMakeLists.txt
> > After undoing the changes the issue is gone.
> 
> No, the change is correct, the paths slightly changed. I fixed the instructions now to say west config manifest.group-filter +bsec2

This could explain the issue because I didn´t run the west command before because I thought the paths were the same. I tested it with west command and it looks good. So please ignore the initial message.

**Comment by Kampi** [comment]
> > > > Got the error
> > > > ```
> > > > ninja: error: '../src/ext_drivers/BSEC2/src/cortex-m4/libalgobsec.a', needed by 'zephyr/zephyr_pre0.elf', missing and no known rule to make it
> > > > FATAL ERROR: command exited with status 1: 'C:\ncs\toolchains\31f4403e35\opt\bin\cmake.EXE' --build 'f:\Git\ZSWatch\app\build_rev_3'
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > when building with BSEC enabled.
> > > 
> > > 
> > > Ok, will check again and also add so there is one build in CI that enables this (or all)
> > 
> > 
> > Looks like the path in the `CMakeLists.txt` of the driver got messed up.
> > https://github.com/jakkra/ZSWatch/blob/main/app/drivers/sensor/bme68x_iaq/CMakeLists.txt
> > After undoing the changes the issue is gone.
> 
> No, the change is correct, the paths slightly changed. I fixed the instructions now to say west config manifest.group-filter +bsec2

This could explain the issue because I didn´t run the west command before because I thought the paths were the same. I tested it with west command and it looks good. So please ignore the initial message.

**Review by Kampi — APPROVED** [review]

**Pull request merged**
