### PR TITLE
Sensor fusion + Speedometer app

### PR DESCRIPTION
**Pull request by ldab**
1. Implement sensor fusion based on https://github.com/xioTechnologies/Fusion
2. A crude speedometer app (haven't really tested on motion) it is cold outside :cold_face: 
3. few todo's but I think we can keep going?

PS. I wanted to keep the screen on, but It does not work, do you know why?

image

### CODE REVIEW

**Comment by Kampi** [comment]
@ldab the screen is handled by `zsw_power_manager`. We don´t have an option to keep the display on yet.

https://github.com/jakkra/ZSWatch/blob/879fbebf9c3e1d4c1cb41e9e2a49df81db8737fc/app/src/managers/zsw_power_manager.c#L61

**Comment by jakkra** [comment]
> @ldab the screen is handled by `zsw_power_manager`. We don´t have an option to keep the display on yet.
> 
> https://github.com/jakkra/ZSWatch/blob/879fbebf9c3e1d4c1cb41e9e2a49df81db8737fc/app/src/managers/zsw_power_manager.c#L61

We do, I have added an option in settings for it, but somehow it's broken now.

Edit: You need to restart for it to take effect.

PS. I think the new flick out need to check for this setting

**Comment by Kampi** [comment]
What unit is the speedometer using? :D

**Comment by Kampi** [comment]
> > What unit is the speedometer using? 😄
> 
> km/h

Can you add a label with the unit to the app?

**Pull request closed without merging**
