### PR TITLE
initial HW tests

### PR DESCRIPTION
**Pull request by ldab**
I have a C brain and the python probably can be done a lot better, but hey, it works: https://github.com/ldab/ZSWatch/actions/runs/9918710328

or better: https://github.com/ldab/ZSWatch/actions/runs/9918813897

### CODE REVIEW

**Comment by ldab** [comment]
sorry for the mess, I'm not well, it should be good now

**Comment by ldab** [comment]
gif

**Comment by jakkra** [comment]
not_bad

**Review by jakkra — APPROVED** [review]

**Comment by Kampi** [comment]
@ldab what´s the purpose of the HW test? I don´t get it :D

**Comment by jakkra** [comment]
> @ldab what´s the purpose of the HW test? I don´t get it :D

For now just testing the FW boots. It's a base to build upp on more.

**Comment by Kampi** [comment]
Ah! That´s cool. So we can add additional HIL tests there I. e. measuring the idle current automatically to see if there is a mismatch.

**Comment by jakkra** [comment]
> Ah! That´s cool. So we can add additional HIL tests there I. e. measuring the idle current automatically to see if there is a mismatch.

Yep everything is possible such as this :)

**Comment by Kampi** [comment]
What is the purpose of the CAN interface? Do you plan to use it for the communication?

**Comment by jakkra** [comment]
> What is the purpose of the CAN interface? Do you plan to use it for the communication?

I think copy paste issue. Requirements comes from Zephyr test requirements I think.

**Comment by ldab** [comment]
> What is the purpose of the CAN interface? Do you plan to use it for the communication?

God no

**Pull request merged**
