### PR TITLE
Add RTC to firmware

### LINKED ISSUE #309: Using the RTC update for the 1s periodic event
Replace the timer for the 1s periodic callback with the RTC update function when using rev 5

image

### PR DESCRIPTION
**Pull request by Kampi**
Closes #309

### CODE REVIEW

**Comment by Kampi** [comment]
@jakkra we have to modify the RTC patch and replace

```
    if (regs[0] & RV8263_BM_OS) {
        return -ECANCELED;
    }
```

with 

```
    /* Clear the oscillator stop flag and return an error when the oscillator is stopped. */
    /* The flag is set again if the error condition for the oscillator is still active. */
    if (regs[0] & RV8263_BM_OS) {
        regs[0] &= ~RV8263_BM_OS;
        i2c_reg_write_byte_dt(&config->i2c_bus, RV8263C8_REGISTER_SECONDS,
                              regs[0]);
        return -ECANCELED;
    }
```

What´s the best way to do it? Can I simply copy+paste this code into the patch?

**Comment by jakkra** [comment]
> @jakkra we have to modify the RTC patch and replace
> 
> ```
>     if (regs[0] & RV8263_BM_OS) {
>         return -ECANCELED;
>     }
> ```
> 
> with 
> 
> ```
>     /* Clear the oscillator stop flag and return an error when the oscillator is stopped. */
>     /* The flag is set again if the error condition for the oscillator is still active. */
>     if (regs[0] & RV8263_BM_OS) {
>         regs[0] &= ~RV8263_BM_OS;
>         i2c_reg_write_byte_dt(&config->i2c_bus, RV8263C8_REGISTER_SECONDS,
>                               regs[0]);
>         return -ECANCELED;
>     }
> ```
> 
> What´s the best way to do it? Can I simply copy+paste this code into the patch?

Idk, try it, see if patch applies correctly otherwise can regenerate the patch

**Comment by Kampi** [comment]
@jakkra I´ve updated the RTC patch to the latest version from Zephyr.

**Comment by jakkra** [comment]
> @jakkra I´ve updated the RTC patch to the latest version from Zephyr to handle the issue with the alarms.

OK great, will test it. Should everything work if I rebase on this branch or do I need to do something more?

**Comment by Kampi** [comment]
I´ve tested it before the new patch and time and update are working. The changes are related to alarms which wasn´t tested by me but I don´t expect any issues.

**Pull request merged**
