### PR TITLE
Move music control to Zbus and remove `#ifdef`

### PR DESCRIPTION
**Pull request by ldab**
`ble_comm.c` could be refactored and some of it moved to `ble_gadgetbridge.c` for example, `music_control_event_callback` looks a bit misplaced now, but it should work

https://github.com/jakkra/ZSWatch/issues/112 ?

### CODE REVIEW

**Comment by jakkra** [comment]
I'm thinking if using zbus for stuff like this is necessary. It's not like this info needs to be propogated around the software, it just goes to either phone "backend". Maybe just a simple API is easier.
For example:
@ldab @Kampi What do you think?
```
// ble_comm.c
#define MAX_BACKENDS 2
ble_comm_backend_cbs backends[MAX_BACKENDS];

ble_comm_register_backend(backend_cbs);

ble_comm_music_control(action) {
    for (int i = 0; i < MAX_BACKENDS; i++) {
        if (ble_comm_backend_cbs[i].music_control) {
            ble_comm_backend_cbs[i].music_control(action);
        }
    }
}

// ble_comm_ios.c

static ble_comm_backend_cbs api = {
    .music_control = music_control,
    .send_battery = send_battery,
    ...
};

ble_comm_register_backend(api);

// ble_comm_gadgetbridge.c

static ble_comm_backend_cbs api = {
    .music_control = music_control,
    .send_battery = send_battery,
    ...
};

ble_comm_register_backend(api);
```

**Comment by ldab** [comment]
> I'm thinking if using zbus for stuff like this is necessary. It's not like this info needs to be propogated around the software, it just goes to either phone "backend". Maybe just a simple API is easier. For example: @ldab @Kampi What do you think?
> 
> ```
> // ble_comm.c
> #define MAX_BACKENDS 2
> ble_comm_backend_cbs backends[MAX_BACKENDS];
> 
> ble_comm_register_backend(backend_cbs);
> 
> ble_comm_music_control(action) {
>     for (int i = 0; i < MAX_BACKENDS; i++) {
>         if (ble_comm_backend_cbs[i].music_control) {
>             ble_comm_backend_cbs[i].music_control(action);
>         }
>     }
> }
> 
> // ble_comm_ios.c
> 
> static ble_comm_backend_cbs api = {
>     .music_control = music_control,
>     .send_battery = send_battery,
>     ...
> };
> 
> ble_comm_register_backend(api);
> 
> // ble_comm_gadgetbridge.c
> 
> static ble_comm_backend_cbs api = {
>     .music_control = music_control,
>     .send_battery = send_battery,
>     ...
> };
> 
> ble_comm_register_backend(api);
> ```

What is the downside of using zbus? I was under the impression that the thing was moving towards not using callbacks, but both solution works.

**Comment by jakkra** [comment]
Possible downside, maybe readability and more boilerplate code to define the zbus events etc.
But on the other hand zbus already handles the code needed in my proposal.

What do you think of just using one event for all phone communication, that will create less boilerplate zbus code. The data type can be an union with an ID?

**Comment by ldab** [comment]
> Possible downside, maybe readability and more boilerplate code to define the zbus events etc. But on the other hand zbus already handles the code needed in my proposal.
> 
> What do you think of just using one event for all phone communication, that will create less boilerplate zbus code. The data type can be an union with an ID? @ldab

I believe @Kampi is working on that on #112

**Comment by jakkra** [comment]
Ok, I'll merge this and then it can be cleaned up to make it same everywhere

**Comment by Kampi** [comment]
@jakkra sounds like a good idea. I had the idea already for BLE connected and disconnected event but it can be expanded with additional stuff. This can also provide some sort of API for the Bluetooth communication in other apps.

**Comment by jakkra** [comment]
> @jakkra sounds like a good idea. I had the idea already for BLE connected and disconnected event but it can be expanded with additional stuff. This can also provide some sort of API for the Bluetooth communication in other apps.

Nice, BUT for the Bluetooth stuff, I think apps should use Zephyr API directly, it has good methods to get callbacks on connect etc. already. This should be used. We can add other stuff related to connections on zbus if we see a need.

**Pull request merged**
